# Generated by Django 4.0.3 on 2022-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_desc', models.CharField(max_length=500000)),
                ('github_link', models.URLField(null=True)),
                ('link_to_demo', models.URLField(null=True)),
                ('project_image', models.URLField(null=True)),
            ],
        ),
    ]
