# Generated by Django 4.0.3 on 2022-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('review', models.TextField()),
                ('img_url', models.URLField(unique=True)),
            ],
        ),
    ]
