# Generated by Django 4.0.3 on 2022-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
